const assert = require("node:assert/strict");
const { chromium } = require("playwright");
const path = require("node:path");
const fs = require("node:fs");
const { randomUUID } = require("node:crypto");
const base = process.env.TEST_BASE_URL || "http://localhost:18787";
const output = process.env.TEST_OUTPUT_DIR ? path.resolve(process.env.TEST_OUTPUT_DIR) : path.resolve(__dirname, "../../test-output");
fs.mkdirSync(output, { recursive: true });

(async () => {
  const browser = await chromium.launch({ channel: "msedge", headless: true });
  const errors = [];
  try {
    const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
    page.on("pageerror", error => errors.push(error.message));
    await page.addInitScript(() => {
      localStorage.setItem("relief-mobile-demo-profile-v2", JSON.stringify({ name: "旧演示账户", email: "legacy@example.com" }));
    });
    await page.goto(base + "/mobile/#market");
    await page.locator('[data-item="MAT-WATER"]').waitFor();
    await page.waitForFunction(() => document.querySelector("#walletSyncStatus").textContent === "未部署");
    assert.equal(await page.locator("#poolMonValue").innerText(), "0");
    assert.equal(await page.locator("#accountName").innerText(), "未登录", "Local demo profiles must not authenticate a user");
    assert.equal((await (await page.request.get(base + "/v1/wallet/me")).json()).data.user, null);
    const email = `workflow-${randomUUID()}@example.com`;
    const password = "Qa-password-".padEnd(128, "x");
    await page.locator("#loginOpenBtn").click();
    assert.equal(await page.locator('#authForm [name="name"]').isVisible(), false, "Default modal must be password login");
    assert.equal(await page.locator('#authForm [name="password"]').getAttribute("minlength"), "10");
    assert.equal(await page.locator('#authForm [name="password"]').getAttribute("maxlength"), "128");
    await page.locator("#authRegisterTab").click();
    await page.locator('#authForm [name="name"]').fill("联调用户");
    await page.locator('#authForm [name="email"]').fill(email);
    await page.locator('#authForm [name="password"]').fill(password);
    await page.locator('#authForm [name="organization"]').fill("浏览器回归测试");
    const registeredPromise = page.waitForResponse(res => res.url().endsWith("/v1/wallet/register") && res.request().method() === "POST");
    await page.locator("#authSubmit").click();
    const registeredResponse = await registeredPromise;
    assert.equal(registeredResponse.status(), 201);
    assert.equal(registeredResponse.request().headers().authorization, undefined, "Registration must not send a demo token");
    assert.equal(registeredResponse.request().postDataJSON().password.length, 128);
    const user = (await registeredResponse.json()).data.user;
    assert.equal(user.name, "联调用户");
    assert.equal(user.email, email);
    assert.equal(user.emailVerified, false);
    assert.equal(user.wallet, null);
    await page.locator("#loginDialog").waitFor({ state: "hidden" });
    assert.equal((await (await page.request.get(base + "/v1/wallet/me")).json()).data.user.id, user.id, "Registration must establish a cookie session");
    await page.locator('.bottom-nav a[href="#account"]').click();
    assert((await page.locator("#accountIdentity").innerText()).includes("邮箱未验证"));
    const loggedOutPromise = page.waitForResponse(res => res.url().endsWith("/v1/wallet/logout") && res.request().method() === "POST");
    await page.locator("#logoutBtn").click();
    assert.equal((await loggedOutPromise).status(), 200);
    await page.waitForFunction(() => document.querySelector("#accountName").textContent === "未登录" && !document.querySelector("#accountAuth").disabled);
    assert.equal((await (await page.request.get(base + "/v1/wallet/me")).json()).data.user, null);
    await page.locator("#loginOpenBtn").click();
    await page.locator("#authLoginTab").click();
    await page.locator('#authForm [name="email"]').fill(email);
    await page.locator('#authForm [name="password"]').fill(password);
    const loggedInPromise = page.waitForResponse(res => res.url().endsWith("/v1/wallet/login") && res.request().method() === "POST");
    await page.locator("#authSubmit").click();
    const loggedInResponse = await loggedInPromise;
    assert.equal(loggedInResponse.status(), 200);
    assert.equal(loggedInResponse.request().headers().authorization, undefined);
    assert.equal((await loggedInResponse.json()).data.user.id, user.id);
    await page.locator("#loginDialog").waitFor({ state: "hidden" });
    await page.reload();
    await page.waitForFunction(() => document.querySelector("#accountName").textContent === "联调用户");
    assert.equal((await (await page.request.get(base + "/v1/wallet/me")).json()).data.user.id, user.id, "Reload must retain the cookie identity");
    assert.equal(await page.locator('#donateFields [name="amountMon"]').isDisabled(), true);
    await page.locator('.bottom-nav a[href="#market"]').click();
    const stockBefore = (await (await page.request.get(base + "/v1/marketplace")).json()).data.find(item => item.id === "MAT-WATER").stock;
    await page.locator('[data-item="MAT-WATER"]').click();
    await page.locator("#orderTask").selectOption("TASK-001");
    await page.locator("#quantityPlus").click();
    assert.equal(await page.locator("#orderTotal").innerText(), "24 MON");
    await page.evaluate(() => { window.__orderInputBeforePoll = document.querySelector("#orderQuantity"); });
    const refreshed = await page.waitForResponse(response => response.url().endsWith("/v1/public/overview") && response.request().method() === "GET");
    await refreshed.finished();
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
    assert.equal(await page.locator("#orderQuantity").inputValue(), "2", "overview refresh preserves quantity draft");
    assert.equal(await page.locator("#orderTask").inputValue(), "TASK-001", "overview refresh preserves task selection");
    assert.equal(await page.evaluate(() => window.__orderInputBeforePoll === document.querySelector("#orderQuantity")), true);
    await page.screenshot({ path: path.join(output, "mobile-product-detail.png") });
    const responsePromise = page.waitForResponse(response => response.url().endsWith("/v1/market-orders") && response.request().method() === "POST");
    await page.locator("#orderSubmit").click();
    const response = await responsePromise;
    assert.equal(response.status(), 201);
    const order = (await response.json()).data;
    assert.equal(order.quantity, 2);
    assert.equal(order.totalMon, 24);
    assert.equal(order.donorUserId, user.id, "Orders must belong to the registered cookie user");
    assert.equal(order.status, "PENDING_REVIEW");
    assert.equal(response.request().headers().authorization, undefined, "Orders must not use demo identity");
    const receiptRefresh = await page.waitForResponse(result => result.url().endsWith("/v1/public/overview") && result.request().method() === "GET");
    await receiptRefresh.finished();
    await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
    await page.locator('#detailContent a[href="#account"]').click();
    await page.waitForFunction(id => document.querySelector("#orderList").textContent.includes(id), order.id);

    const admin = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    admin.on("pageerror", error => errors.push(error.message));
    await admin.goto(base + "/admin/#market-orders");
    assert.ok(process.env.TEST_ADMIN_TOKEN, "Set TEST_ADMIN_TOKEN for the isolated legacy test server");
    await admin.locator("#waToken").fill(process.env.TEST_ADMIN_TOKEN);
    await admin.locator('#waLogin button[type="submit"]').click();
    const approve = admin.locator(`[data-order="${order.id}"][data-action="approve"]`);
    await approve.waitFor();
    const approvedPromise = admin.waitForResponse(res => res.url().endsWith(`/v1/market-orders/${order.id}/approve`));
    await approve.click();
    const approvedResponse = await approvedPromise;
    assert.equal(approvedResponse.status(), 200);
    const approved = (await approvedResponse.json()).data;
    assert.equal(approved.status, "APPROVED");
    assert(approved.contractId);
    await admin.waitForFunction(id => document.querySelector("#marketOrderRows").textContent.includes(id), approved.contractId);
    await admin.locator("#market-orders").scrollIntoViewIfNeeded();
    await admin.screenshot({ path: path.join(output, "admin-approved-order.png") });
    await page.locator("#accountRetry").click();
    await page.waitForFunction(id => document.querySelector("#orderList").textContent.includes(id), approved.contractId);
    await page.locator(`[data-contract="${approved.contractId}"]`).click();
    await page.waitForFunction(id => document.querySelector("#detailContent").textContent.includes(id), approved.contractId);
    await page.locator('#detailDialog [data-close]').click();
    await page.screenshot({ path: path.join(output, "mobile-approved-order.png"), fullPage: true });
    await page.reload();
    await page.waitForFunction(id => document.querySelector("#orderList").textContent.includes(id), approved.contractId);
    await page.locator('.bottom-nav a[href="#market"]').click();
    const product = page.locator("#marketList article").filter({ has: page.locator('[data-item="MAT-WATER"]') });
    const catalog = await (await fetch(base + "/v1/marketplace")).json();
    const stock = catalog.data.find(item => item.id === "MAT-WATER").stock;
    assert.equal(stock, stockBefore - 2, "Approval must consume the requested stock exactly once");
    await page.waitForFunction(stockText => document.querySelector('[data-item="MAT-WATER"]').closest("article").textContent.includes(stockText), stock.toLocaleString("zh-CN"));
    assert((await product.innerText()).includes(stock.toLocaleString("zh-CN")));
    await page.locator('.bottom-nav a[href="#home"]').click();
    await page.locator('[data-article]').first().click();
    assert((await page.locator("#detailContent a[target=_blank]").count()) > 0);
    await page.screenshot({ path: path.join(output, "mobile-news-detail.png") });
    await page.locator('#detailDialog [data-close]').click();
    const before = await page.locator("#poolMonValue").innerText();
    assert.equal(before, "0", "Order approval and catalogue refresh must not credit the real wallet pool");
    await page.route("**/v1/public/overview", route => route.abort());
    await page.locator("#retryBtn").click();
    await page.waitForFunction(() => document.querySelector("#connection").dataset.state === "error");
    assert.equal(await page.locator("#poolMonValue").innerText(), before, "Disconnected balance must not change");
    await page.unroute("**/v1/public/overview");
    await page.locator("#retryBtn").click();
    await page.waitForFunction(() => document.querySelector("#connection").dataset.state === "online");
    assert.equal(await page.locator("#poolMonValue").innerText(), "0");
    assert.equal(await page.locator("#walletSyncStatus").innerText(), "未部署");
    assert.deepEqual(errors, []);
    console.log("Browser registration -> login -> cookie order -> admin approval -> contract -> mobile sync; undeployed pool stays zero PASS", order.id, approved.contractId);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
